org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Limite la mémoire globale de Gradle à 1,5 Go (au lieu des 3 ou 4 Go par défaut)
org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=384m

# Désactive le fonctionnement en arrière-plan pour libérer la RAM dès que possible
org.gradle.daemon=false

# Force le compilateur Kotlin à s'exécuter dans le même processus pour économiser la RAM
kotlin.compiler.execution.strategy=in-process

